# Generated by Django 5.1.6 on 2025-02-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainpageImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
            ],
            options={
                "verbose_name": "Картинка для главной",
                "verbose_name_plural": "Картинки для главной",
                "db_table": "meinpage_images",
            },
        ),
    ]
