# Generated by Django 5.1.6 on 2025-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024, verbose_name="Заголовок")),
                ("start_datetime", models.DateTimeField(verbose_name="Время начала")),
                ("end_datetime", models.DateTimeField(verbose_name="Время начала")),
                ("address", models.CharField(max_length=1024, verbose_name="Адрес")),
                (
                    "vk_event",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Встреча ВК",
                    ),
                ),
                (
                    "tickets_link",
                    models.CharField(max_length=2048, verbose_name="Ссылка на билеты"),
                ),
            ],
            options={
                "verbose_name": "Концерт",
                "verbose_name_plural": "Концерты",
                "db_table": "concerts",
            },
        ),
    ]
