# Generated by Django 5.1.6 on 2025-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="poster",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
